import { useState, type FormEvent } from "react";
import { Edit3, Lock, Pin, PinOff, Plus, Trash2, Unlock } from "lucide-react";
import { useAdminAccess } from "../components/AdminAccess";
import { Badge, Button, ConfirmButton, EmptyState, ErrorState, IconButton, LoadingState, Modal, PageHeader } from "../components/ui";
import { formatDate } from "../lib/format";
import { deleteNCreatePost, deleteNCreateTopic, getNCreateCategories, getNCreatePosts, getNCreateTopics, saveNCreateCategory, updateNCreatePost, updateNCreateTopic } from "../lib/ncreate-data";
import type { NCreateForumCategory, NCreatePostView } from "../lib/types";
import { useAsync } from "../lib/useAsync";

type Tab = "categories" | "topics" | "posts";

export function NCreateForumPage() {
  const { role } = useAdminAccess();
  const canManageCategories = role === "admin" || role === "owner";
  const [tab, setTab] = useState<Tab>(canManageCategories ? "categories" : "topics");
  const categories = useAsync(getNCreateCategories);
  const topics = useAsync(getNCreateTopics);
  const posts = useAsync(getNCreatePosts);
  const [editingCategory, setEditingCategory] = useState<NCreateForumCategory | "new" | null>(null);
  const [editingPost, setEditingPost] = useState<NCreatePostView | null>(null);
  const [error, setError] = useState("");
  const perform = async (action: () => Promise<void>, reload: () => Promise<void>) => { setError(""); try { await action(); await reload(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed"); return false; } };
  const submitCategory = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const item = editingCategory === "new" ? null : editingCategory; const saved = await perform(() => saveNCreateCategory(item?.id ?? null, { name: String(form.get("name")).trim(), slug: String(form.get("slug")).trim(), description: String(form.get("description")).trim() || null, sort_order: Number(form.get("sort_order")), is_active: form.get("is_active") === "on" }), categories.reload); if (saved) setEditingCategory(null); };
  const submitPost = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editingPost) return; const body = String(new FormData(event.currentTarget).get("body")).trim(); const saved = await perform(() => updateNCreatePost(editingPost.id, { body }), posts.reload); if (saved) setEditingPost(null); };
  const current = tab === "categories" ? categories : tab === "topics" ? topics : posts;
  return <><PageHeader controlLabel="NCREATE CONTROL" title="Forum" description="Категории, темы и ответы только форума NCreate." action={tab === "categories" && canManageCategories ? <Button onClick={() => setEditingCategory("new")}><Plus size={17} />Новая категория</Button> : undefined} /><div className="tabs" role="tablist">{(canManageCategories ? ["categories","topics","posts"] : ["topics","posts"]).map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item as Tab)} key={item}>{item}</button>)}</div>{error && <ErrorState message={error} />}{current.loading && <LoadingState />}{current.error && <ErrorState message={current.error} retry={current.reload} />}
  {tab === "categories" && categories.data && (categories.data.length ? <div className="table-wrap"><table><thead><tr><th>Category</th><th>Slug</th><th>Order</th><th>Status</th><th /></tr></thead><tbody>{categories.data.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.description ?? "Скоро будет"}</small></td><td className="mono">{item.slug}</td><td>{item.sort_order}</td><td><Badge tone={item.is_active ? "live" : "muted"}>{item.is_active ? "active" : "inactive"}</Badge></td><td><IconButton aria-label={`Edit ${item.name}`} onClick={() => setEditingCategory(item)}><Edit3 size={17} /></IconButton></td></tr>)}</tbody></table></div> : <EmptyState title="Категорий пока нет" detail="Создайте первую категорию без фиктивных тем." />)}
  {tab === "topics" && topics.data && (topics.data.length ? <div className="table-wrap"><table><thead><tr><th>Topic</th><th>Author</th><th>Created</th><th>State</th><th>Actions</th></tr></thead><tbody>{topics.data.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.category}</small></td><td>@{item.author}</td><td>{formatDate(item.created_at)}</td><td><div className="badge-row">{item.is_pinned && <Badge tone="live">pinned</Badge>}{item.is_locked && <Badge tone="warning">locked</Badge>}{!item.is_pinned && !item.is_locked && <Badge>open</Badge>}</div></td><td><div className="action-row"><IconButton aria-label={item.is_pinned ? "Unpin" : "Pin"} onClick={() => void perform(() => updateNCreateTopic(item.id, { is_pinned: !item.is_pinned }), topics.reload)}>{item.is_pinned ? <PinOff size={17} /> : <Pin size={17} />}</IconButton><IconButton aria-label={item.is_locked ? "Unlock" : "Lock"} onClick={() => void perform(() => updateNCreateTopic(item.id, { is_locked: !item.is_locked }), topics.reload)}>{item.is_locked ? <Unlock size={17} /> : <Lock size={17} />}</IconButton><ConfirmButton confirmLabel="Скрыть тему NCreate?" onConfirm={() => perform(() => deleteNCreateTopic(item.id), topics.reload)}><Trash2 size={15} /></ConfirmButton></div></td></tr>)}</tbody></table></div> : <EmptyState title="Тем пока нет" detail="Пользователи смогут создать темы после появления категорий." />)}
  {tab === "posts" && posts.data && (posts.data.length ? <div className="table-wrap"><table><thead><tr><th>Post</th><th>Topic</th><th>Author</th><th>Created</th><th>Actions</th></tr></thead><tbody>{posts.data.map((item) => <tr key={item.id}><td className="truncate-cell">{item.body}</td><td>{item.topic}</td><td>@{item.author}</td><td>{formatDate(item.created_at)}</td><td><div className="action-row"><IconButton aria-label="Edit post" onClick={() => setEditingPost(item)}><Edit3 size={17} /></IconButton><ConfirmButton confirmLabel="Скрыть ответ NCreate?" onConfirm={() => perform(() => deleteNCreatePost(item.id), posts.reload)}><Trash2 size={15} /></ConfirmButton></div></td></tr>)}</tbody></table></div> : <EmptyState title="Ответов пока нет" detail="Скоро будет" />)}
  {editingCategory && <Modal title={editingCategory === "new" ? "Новая категория NCreate" : "Редактировать категорию"} onClose={() => setEditingCategory(null)}><form className="modal-form" onSubmit={(event) => void submitCategory(event)}><label><span>Name</span><input name="name" defaultValue={editingCategory === "new" ? "" : editingCategory.name} required /></label><label><span>Slug</span><input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={editingCategory === "new" ? "" : editingCategory.slug} required /></label><label><span>Description</span><textarea name="description" defaultValue={editingCategory === "new" ? "" : editingCategory.description ?? ""} /></label><label><span>Order</span><input name="sort_order" type="number" defaultValue={editingCategory === "new" ? 0 : editingCategory.sort_order} /></label><label className="check"><input name="is_active" type="checkbox" defaultChecked={editingCategory === "new" || editingCategory.is_active} />Active</label><Button type="submit">Сохранить</Button></form></Modal>}
  {editingPost && <Modal title="Редактировать ответ NCreate" onClose={() => setEditingPost(null)} wide><form className="modal-form" onSubmit={(event) => void submitPost(event)}><label><span>Body</span><textarea name="body" rows={12} defaultValue={editingPost.body} required /></label><Button type="submit">Сохранить</Button></form></Modal>}</>;
}
