/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DesignRouteImport } from './routes/design'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FancymenuRouteImport } from './routes/fancymenu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ModpacksRouteImport } from './routes/modpacks'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResourcepacksRouteImport } from './routes/resourcepacks'
import { Route as ServerSetupRouteImport } from './routes/server-setup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as MarketplaceMyRouteImport } from './routes/marketplace.my'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as ForumCategorySlugRouteImport } from './routes/forum.category.$slug'
import { Route as ForumTopicSlugRouteImport } from './routes/forum.topic.$slug'
import { Route as MarketplaceSlugEditRouteImport } from './routes/marketplace_.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FancymenuRoute = FancymenuRouteImport.update({
  id: '/fancymenu',
  path: '/fancymenu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksRoute = ModpacksRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcepacksRoute = ResourcepacksRouteImport.update({
  id: '/resourcepacks',
  path: '/resourcepacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSetupRoute = ServerSetupRouteImport.update({
  id: '/server-setup',
  path: '/server-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceMyRoute = MarketplaceMyRouteImport.update({
  id: '/marketplace/my',
  path: '/marketplace/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/marketplace/new',
  path: '/marketplace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCategorySlugRoute = ForumCategorySlugRouteImport.update({
  id: '/forum/category/$slug',
  path: '/forum/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicSlugRoute = ForumTopicSlugRouteImport.update({
  id: '/forum/topic/$slug',
  path: '/forum/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugEditRoute = MarketplaceSlugEditRouteImport.update({
  id: '/marketplace_/$slug/edit',
  path: '/marketplace/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/events': typeof EventsRoute
  '/fancymenu': typeof FancymenuRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/maps': typeof MapsRoute
  '/modpacks': typeof ModpacksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resourcepacks': typeof ResourcepacksRoute
  '/server-setup': typeof ServerSetupRoute
  '/services': typeof ServicesRoute
  '/skins': typeof SkinsRoute
  '/support': typeof SupportRoute
  '/websites': typeof WebsitesRoute
  '/workers': typeof WorkersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/forum/': typeof ForumIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/marketplace/$slug/edit': typeof MarketplaceSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/events': typeof EventsRoute
  '/fancymenu': typeof FancymenuRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/maps': typeof MapsRoute
  '/modpacks': typeof ModpacksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resourcepacks': typeof ResourcepacksRoute
  '/server-setup': typeof ServerSetupRoute
  '/services': typeof ServicesRoute
  '/skins': typeof SkinsRoute
  '/support': typeof SupportRoute
  '/websites': typeof WebsitesRoute
  '/workers': typeof WorkersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/forum': typeof ForumIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/marketplace/$slug/edit': typeof MarketplaceSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/events': typeof EventsRoute
  '/fancymenu': typeof FancymenuRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/maps': typeof MapsRoute
  '/modpacks': typeof ModpacksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resourcepacks': typeof ResourcepacksRoute
  '/server-setup': typeof ServerSetupRoute
  '/services': typeof ServicesRoute
  '/skins': typeof SkinsRoute
  '/support': typeof SupportRoute
  '/websites': typeof WebsitesRoute
  '/workers': typeof WorkersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/forum/': typeof ForumIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/forum/category/$slug': typeof ForumCategorySlugRoute
  '/forum/topic/$slug': typeof ForumTopicSlugRoute
  '/marketplace_/$slug/edit': typeof MarketplaceSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design'
    | '/events'
    | '/fancymenu'
    | '/login'
    | '/logos'
    | '/maps'
    | '/modpacks'
    | '/plugins'
    | '/profile'
    | '/register'
    | '/resourcepacks'
    | '/server-setup'
    | '/services'
    | '/skins'
    | '/support'
    | '/websites'
    | '/workers'
    | '/marketplace/$slug'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/forum/'
    | '/marketplace/'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
    | '/marketplace/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/design'
    | '/events'
    | '/fancymenu'
    | '/login'
    | '/logos'
    | '/maps'
    | '/modpacks'
    | '/plugins'
    | '/profile'
    | '/register'
    | '/resourcepacks'
    | '/server-setup'
    | '/services'
    | '/skins'
    | '/support'
    | '/websites'
    | '/workers'
    | '/marketplace/$slug'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/forum'
    | '/marketplace'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
    | '/marketplace/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design'
    | '/events'
    | '/fancymenu'
    | '/login'
    | '/logos'
    | '/maps'
    | '/modpacks'
    | '/plugins'
    | '/profile'
    | '/register'
    | '/resourcepacks'
    | '/server-setup'
    | '/services'
    | '/skins'
    | '/support'
    | '/websites'
    | '/workers'
    | '/marketplace/$slug'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/forum/'
    | '/marketplace/'
    | '/forum/category/$slug'
    | '/forum/topic/$slug'
    | '/marketplace_/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DesignRoute: typeof DesignRoute
  EventsRoute: typeof EventsRoute
  FancymenuRoute: typeof FancymenuRoute
  LoginRoute: typeof LoginRoute
  LogosRoute: typeof LogosRoute
  MapsRoute: typeof MapsRoute
  ModpacksRoute: typeof ModpacksRoute
  PluginsRoute: typeof PluginsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResourcepacksRoute: typeof ResourcepacksRoute
  ServerSetupRoute: typeof ServerSetupRoute
  ServicesRoute: typeof ServicesRoute
  SkinsRoute: typeof SkinsRoute
  SupportRoute: typeof SupportRoute
  WebsitesRoute: typeof WebsitesRoute
  WorkersRoute: typeof WorkersRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  MarketplaceMyRoute: typeof MarketplaceMyRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  ForumIndexRoute: typeof ForumIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ForumCategorySlugRoute: typeof ForumCategorySlugRoute
  ForumTopicSlugRoute: typeof ForumTopicSlugRoute
  MarketplaceSlugEditRoute: typeof MarketplaceSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fancymenu': {
      id: '/fancymenu'
      path: '/fancymenu'
      fullPath: '/fancymenu'
      preLoaderRoute: typeof FancymenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks': {
      id: '/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resourcepacks': {
      id: '/resourcepacks'
      path: '/resourcepacks'
      fullPath: '/resourcepacks'
      preLoaderRoute: typeof ResourcepacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-setup': {
      id: '/server-setup'
      path: '/server-setup'
      fullPath: '/server-setup'
      preLoaderRoute: typeof ServerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/my': {
      id: '/marketplace/my'
      path: '/marketplace/my'
      fullPath: '/marketplace/my'
      preLoaderRoute: typeof MarketplaceMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/category/$slug': {
      id: '/forum/category/$slug'
      path: '/forum/category/$slug'
      fullPath: '/forum/category/$slug'
      preLoaderRoute: typeof ForumCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/topic/$slug': {
      id: '/forum/topic/$slug'
      path: '/forum/topic/$slug'
      fullPath: '/forum/topic/$slug'
      preLoaderRoute: typeof ForumTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/$slug/edit': {
      id: '/marketplace_/$slug/edit'
      path: '/marketplace/$slug/edit'
      fullPath: '/marketplace/$slug/edit'
      preLoaderRoute: typeof MarketplaceSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DesignRoute: DesignRoute,
  EventsRoute: EventsRoute,
  FancymenuRoute: FancymenuRoute,
  LoginRoute: LoginRoute,
  LogosRoute: LogosRoute,
  MapsRoute: MapsRoute,
  ModpacksRoute: ModpacksRoute,
  PluginsRoute: PluginsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResourcepacksRoute: ResourcepacksRoute,
  ServerSetupRoute: ServerSetupRoute,
  ServicesRoute: ServicesRoute,
  SkinsRoute: SkinsRoute,
  SupportRoute: SupportRoute,
  WebsitesRoute: WebsitesRoute,
  WorkersRoute: WorkersRoute,
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  MarketplaceMyRoute: MarketplaceMyRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
  ForumIndexRoute: ForumIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ForumCategorySlugRoute: ForumCategorySlugRoute,
  ForumTopicSlugRoute: ForumTopicSlugRoute,
  MarketplaceSlugEditRoute: MarketplaceSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
