create type public.app_role as enum ('user', 'moderator', 'admin');
create type public.marketplace_listing_status as enum ('draft', 'published', 'archived');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 32),
  display_name text check (display_name is null or char_length(display_name) <= 80),
  avatar_url text,
  bio text check (bio is null or char_length(bio) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.user_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);
create table public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null check (char_length(name) between 1 and 80),
  description text check (description is null or char_length(description) <= 280),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table public.forum_topics (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.forum_categories (id),
  author_id uuid not null references public.profiles (id),
  title text not null check (char_length(title) between 3 and 180),
  slug text not null,
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, slug)
);
create table public.forum_posts (
  id uuid primary key default gen_random_uuid(),
  topic_id uuid not null references public.forum_topics (id) on delete cascade,
  author_id uuid not null references public.profiles (id),
  body text not null check (char_length(body) between 1 and 20000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.marketplace_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null check (char_length(name) between 1 and 80),
  description text check (description is null or char_length(description) <= 280),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.marketplace_categories (id),
  seller_id uuid not null references public.profiles (id),
  title text not null check (char_length(title) between 3 and 180),
  slug text not null unique,
  description text not null check (char_length(description) between 1 and 20000),
  price_amount numeric(12, 2) check (price_amount is null or price_amount >= 0),
  currency_code text not null default 'RUB' check (currency_code ~ '^[A-Z]{3}$'),
  status public.marketplace_listing_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.marketplace_listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.marketplace_listings (id) on delete cascade,
  storage_path text not null,
  alt_text text check (alt_text is null or char_length(alt_text) <= 180),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (listing_id, storage_path)
);

create index forum_topics_category_id_idx on public.forum_topics (category_id);
create index forum_topics_author_id_idx on public.forum_topics (author_id);
create index forum_posts_topic_id_idx on public.forum_posts (topic_id);
create index forum_posts_author_id_idx on public.forum_posts (author_id);
create index marketplace_listings_category_id_idx on public.marketplace_listings (category_id);
create index marketplace_listings_seller_id_idx on public.marketplace_listings (seller_id);
create index marketplace_listing_images_listing_id_idx on public.marketplace_listing_images (listing_id);

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.forum_categories enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;
alter table public.marketplace_categories enable row level security;
alter table public.marketplace_listings enable row level security;
alter table public.marketplace_listing_images enable row level security;

revoke all on table public.profiles, public.user_roles, public.forum_categories,
  public.forum_topics, public.forum_posts, public.marketplace_categories,
  public.marketplace_listings, public.marketplace_listing_images from anon, authenticated;
grant select on table public.profiles, public.forum_categories, public.marketplace_categories,
  public.marketplace_listings, public.marketplace_listing_images to anon, authenticated;
grant usage on type public.app_role to authenticated;
grant usage on type public.marketplace_listing_status to anon, authenticated;

create policy "Public profiles are readable" on public.profiles
  for select to anon, authenticated using (true);
create policy "Active forum categories are readable" on public.forum_categories
  for select to anon, authenticated using (is_active);
create policy "Active marketplace categories are readable" on public.marketplace_categories
  for select to anon, authenticated using (is_active);
create policy "Published listings are readable" on public.marketplace_listings
  for select to anon, authenticated using (status = 'published');
create policy "Published listing images are readable" on public.marketplace_listing_images
  for select to anon, authenticated using (
    exists (
      select 1 from public.marketplace_listings
      where marketplace_listings.id = marketplace_listing_images.listing_id
        and marketplace_listings.status = 'published'
    )
  );
